accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',views.LoginView.as_view(),name='login'),
    path('guest_checkout/',views.GuestRegisterView.as_view(),name='guest_checkout'),
    path('register/',views.SignUp.as_view(),name='register'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('accounts/',views.AccountHomeView.as_view(),name='home')

]

addresses/urls.py
from django.urls import path
from . import views

app_name = 'addresses'

urlpatterns = [
    path('checkout/address/create/',views.checkout_address_create_view,name='checkout_address_create'),
    path('checkout/address/reuse/',views.checkout_address_reuse,name='checkout_address_reuse')
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('carts/',views.cart_home,name='cart'),
    path('cart_update/',views.cart_update,name='cart_update'),
    path('checkout/',views.checkout,name='checkout'),
    path('checkout/done',views.checkout_done_view,name='checkout_done'),
    path('api/cart/',views.api_cart_remove_view,name='api_cart_remove')

]

products/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'products'

urlpatterns = [
    path('products/',views.ProductListView.as_view(),name='product'),
    path('featured/',views.ProductFeaturedList.as_view(),name='featured'),

    #path('products/<str:pk>/',views.ProductDetailView.as_view()),
    path('featured/<str:pk>/',views.ProductFeaturedDetail.as_view(),name='singleFeatured'),
    path('products/<slug:slug>/',views.ProductDetailSlugView.as_view(),name='singleProduct')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#above code displays files uploaded

carts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import m2m_changed,pre_save,post_save

User = settings.AUTH_USER_MODEL

from products.models import Product

#creating model manager
class CartManager(models.Manager):

    def new(self,user=None):
        #create a cart with user or none
        #check if user is there and authenticated
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                #left user is just variable
                #right user is logged in user sent via views with request.user
                user_obj = user

        return self.model.objects.create(user=user_obj)

    #if cart is not create cart, if cart is, but no user, then create user,
    #if cart and user, then get that cart
    def new_or_get(self,request):
        #get the cart id if there is, or set to None
        cart_id = request.session.get('cart_id',None)
        #get cart object with that cart id
        qs = self.get_queryset().filter(id=cart_id)
        if qs.exists():
            new_obj = False
            cart_obj = qs.first()
            if cart_obj.user is None and request.user.is_authenticated:
                cart_obj.user = request.user
                cart_obj.save()

        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            #set the session
            request.session['cart_id'] = cart_obj.id

        return cart_obj,new_obj

# Create your models here.
class Cart(models.Model):
    user    = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    products= models.ManyToManyField(Product, blank=True)
    subtotal   = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total   = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    #creating the objects of model manager
    objects = CartManager()

    def __str__(self):
        return str(self.id)

#creating signal to calculate the price of products in the cart
def m2m_changed__cart_receiver(instance,sender, action,*args,**kwargs):
    #this is from documentation
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        #get all the products from cart
        products = instance.products.all()
        total = 0
        for product in products:
            total += product.price
            if instance.subtotal != total:
                #if both are same then, we will not save
                #subtotal is like changing according to products
                #total is like total amount all together
                instance.subtotal = total
                #save to cart with total
                instance.save()

#above we do save() because it doesnot save automatically
m2m_changed.connect(m2m_changed__cart_receiver,sender=Cart.products.through)

#signals for saving Cart
def pre_save_cart_receiver(instance,sender,*args,**kwargs):
    #here we can use 10% vat
    instance.total = float(instance.subtotal) * float(1.08)

pre_save.connect(pre_save_cart_receiver,sender=Cart)

carts/views.py
from django.http import JsonResponse

from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from accounts.forms import LoginForm,GuestForm
from addresses.forms import AddressForm

from .models import Cart
from orders.models import Order
from products.models import Product
from billing.models import BillingProfile
from accounts.models import GuestEmail
from addresses.models import Address

#importing stripe key
import stripe
stripe.api_key = "sk_test_51IiZrxKWI8M2i0OA25Ei7UFoIxtV3g23VSn3MWurpHOefiAvwHRVy0QwSPJjSy2qwok8mH06Qo9ZUXLaiDPNjcP200JDz95LFB"

def api_cart_remove_view(request):
    cart_obj,new_obj = Cart.objects.new_or_get(request)
    products = cart_obj.products.all()

    #json only take data in form of dictionary so we convert products detail into dictionary
    products = [
        {
            'id':product.id,
            'url':product.get_absolute_url(),
            'name':product.title,
            'price':product.price
        }
        for product in products
    ]

    #send json response to data, which data need to be refresh via ajax
    cart_data = {
        'product':products,
        'subtotal':cart_obj.subtotal,
        'total':cart_obj.total
        }
    return JsonResponse(cart_data)

# Create your views here.
def cart_home(request):
    #using model Manager
    #so that we can use the cart_obj anywhere if we need to use that session id
    cart_obj, new_obj = Cart.objects.new_or_get(request)

    return render(request,'carts/home.html',{'cart':cart_obj})

def cart_update(request):
    #receive id from POST method using form
    product_id = request.POST['product_id']
    product = Product.objects.get(id=product_id)
    #getting card or creating if not
    cart_obj,new_obj = Cart.objects.new_or_get(request)

    #check if product is alreay in there:
    if product in cart_obj.products.all():
        cart_obj.products.remove(product)
        added = False
    else:
        #adding received product to cart
        cart_obj.products.add(product)
        added = True
        #as we want to see cart items total in everypage so we store in session and displays in navbar
    request.session['cart_items'] = cart_obj.products.count()

    #if data is sent via ajax
    if request.is_ajax():
        json_data = {
            'added':added,
            'removed':not added,
            'cartProductCount':cart_obj.products.count(),
        }
        return JsonResponse(json_data)

    return redirect ('carts:cart')

def checkout(request):
    #new_obj is boolean field
    #these none we have to create because error will pop up as it is passes via context
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect('carts:cart')

    login_form = LoginForm(request=request)
    guest_form = GuestForm()
    address_form = AddressForm()

    billing_address_id = request.session.get("billing_address_id",None)
    shipping_address_id = request.session.get("shipping_address_id",None)

    #creating billing profile using model Manager
    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)

    #behind the scene we need to create the order, on the basis of billing profile, cart and set that order to true
    #here definitely there is billing profile from above
    #order is created using model manager
    address_qs = None
    if billing_profile is not None:

        #get the address detail of same billing profile
        address_qs = Address.objects.filter(billing_profile=billing_profile)

        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile,cart_obj)

        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id)
        if shipping_address_id or billing_address_id:
            order_obj.save()

    if request.method == 'POST':

        if order_obj.check_done():
            order_obj.mark_paid()
            print(order_obj.mark_paid())
            request.session['cart_items']=0
            del request.session['cart_id']
            return redirect('carts:checkout_done')


    context = {
        'object':order_obj,
        'billing_profile':billing_profile,
        'login_form':login_form,
        'guest_form':guest_form,
        'next_url':request.build_absolute_uri,
        'address_form':address_form,
        'address_qs':address_qs
    }

    return render(request,'carts/checkout.html',context)


def checkout_done_view(request):
    return render(request,'carts/checkout_done.html',{})

carts/templates/carts/checkout.html
{% extends 'base.html' %}

{% block content %}

{% if not billing_profile %}
  <p>Log In</p>
  {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}

  <p>Check Out as guest</p>
  {% url 'accounts:guest_checkout' as guest_checkout_url %}
  {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_checkout_url %}

{% else %}

  {% if not object.shipping_address %}
      <p class="lead">Shipping Address</p>
      <hr>
      <div class="row">
        <div class="col-md-6">
          {% url 'addresses:checkout_address_create' as checkout_address_create %}
          {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_address_create %}
        </div>

        <div class="col-md-6">
          {% if request.user.is_authenticated %}
          {% url 'addresses:checkout_address_reuse' as checkout_address_reuse %}
          {% include 'addresses/reuse_address_form.html' with next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_address_reuse %}
          {% endif %}
        </div>

  {% elif not object.billing_address %}

    <p class="lead">Billing Address</p>
    <hr>
    <div class="row">
      <div class="col col-md-6">
        {% url 'addresses:checkout_address_create' as checkout_address_create %}
        {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri address_type='billing' action_url=checkout_address_create %}
      </div>

    <div class="col col-md-6">
        {% if request.user.is_authenticated %}
      {% url 'addresses:checkout_address_reuse' as checkout_address_reuse %}
      {% include 'addresses/reuse_address_form.html' with next_url=request.build_absolute_uri address_type='billing' action_url=checkout_address_reuse %}
      {% endif %}
    </div>
  </div>

  {% else %}

    <p>Cart Items: {% for product in object.cart.products.all %} {{product}} {% endfor %} </p>
    <!-- using the function to get all the field of address -->
    <p>Shipping Address: {{object.shipping_address.get_address}}</p>
    <p>Billing Address: {{object.billing_address.get_address}}</p>

    <p>Cart Total: {{object.cart.total}}</p>
    <p>Shipping Total:{{object.shipping_total}}</p>
    <p>Total:  {{object.total}}</p>

    <form method="post" action="">
      {% csrf_token %}
      <button type="submit" class="btn btn-success">Checkout</button>
    </form>

  {% endif%}

{% endif %}

{% endblock %}

carts/templates/carts/checkout_done.html
{% extends 'base.html' %}

{% block content %}

  <h1>thank You for your order!</h1>  

{% endblock %}

carts/templates/carts/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Cart</h1>

{% if cart.products.exists %}
  <table class="table cart-table">
    <thead>
      <tr>
        <th>#</th>
        <th>Product Name</th>
        <th>Product Price</th>
      </tr>
    </thead>
    <tbody class="cart-body">
      {% for product in cart.products.all %}
      <tr class="cart-product">
        <td>{{ forloop.counter }}</td>
        <td><a href="{% url 'products:singleProduct' slug=product.slug %}">{{ product.title }}</a>
        <!-- using form to delete the product using post method -->
        {% include 'carts/snippets/product-remove-cart.html' with product_id=product.id %}
        </td>
        <td>{{ product.price }}</td>

      </tr>
      {% endfor %}
      <tr>
        <th colspan="2"></th>
        <td><b>Subtotal</b><span class="cart-subtotal">{{ cart.subtotal }}</span></td>
      </tr>
      <tr>
        <th colspan="2"></th>
        <td><b>Total</b><span class="cart-total">{{ cart.total }}</span></td>
      </tr>
      <tr>
        <th colspan="2"></th>
        <td><a href="{% url 'carts:checkout' %}"><button class="btn btn-lg btn-success">Checkout</button></a><td>
      </tr>
    </tbody>
  </table>

  <!-- this form is for jquery to display the button after remove is clicked, it is hidden initially and after rmeove is clicked that remove disappears and it shows up -->
  <div class="cart-item-remove-form" style="display:none">
    {% include 'carts/snippets/product-remove-cart.html' with product_id=product.id %}
  </div>

{% else %}
  <p class="lead">Carts empty</p>
{% endif %}

{% endblock %}