accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',views.LoginView.as_view(),name='login'),
    path('guest_checkout/',views.GuestRegisterView.as_view(),name='guest_checkout'),
    path('register/',views.SignUp.as_view(),name='register'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('accounts/',views.AccountHomeView.as_view(),name='home')

]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('carts/',views.cart_home,name='cart'),
    path('cart_update/',views.cart_update,name='cart_update'),
    path('checkout/',views.checkout,name='checkout'),
    path('checkout/done',views.checkout_done_view,name='checkout_done'),
    path('api/cart/',views.api_cart_remove_view,name='api_cart_remove')

]

products/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'products'

urlpatterns = [
    path('products/',views.ProductListView.as_view(),name='product'),
    path('featured/',views.ProductFeaturedList.as_view(),name='featured'),

    #path('products/<str:pk>/',views.ProductDetailView.as_view()),
    path('featured/<str:pk>/',views.ProductFeaturedDetail.as_view(),name='singleFeatured'),
    path('products/<slug:slug>/',views.ProductDetailSlugView.as_view(),name='singleProduct')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#above code displays files uploaded

templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

templates/base/js.html
{% load static %}

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/c42320c6c6.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>


<!-- custom ecoomerce -->
<script src="{% static 'js/ecommerce.js' %}"></script>

<!-- javascript cookie -->
<script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
<script src="{% static 'js/ecommerce-csrf-ajax.js' %}"></script>

templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'products:product' as product_url %}
{% url 'contact' as contact_url %}
{% url 'carts:cart' as carts_url %}
{% url 'cart:home' as cart_url %}
{% url 'accounts:register' as register_url %}
{% url 'accounts:login' as login_url %}
{% url 'accounts:home' as home_url %}



<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">

    <a class="navbar-brand" href="#">E commerce</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item {% if request.path == home_url %} active {% endif %}">
          <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item {% if request.path == product_url %} active {% endif %}" >
          <a class="nav-link" href="{% url 'products:product' %}">Products</a>
        </li>
        <li class="nav-item {% if request.path == contact_url %} active {% endif %}" >
          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
        </li>

        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item {% if request.path == home_url %} active {% endif %}" href="{% url 'accounts:home' %}
          ">Home</a>
          <a class="dropdown-item" href="#">Billing</a>
          <a class="dropdown-item" href="#">Preferences</a>
          <a class="dropdown-item" href="#">History</a>

          <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log Out</a>
        </div>
      </li>
        {% else %}
        <li class="nav-item {% if request.path == login_url %} active {% endif %}">
          <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
        </li>
        <li class="nav-item {% if request.path == register_url %} active {% endif %}">
          <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
        </li>
        {% endif %}
        <li class="nav-item {% if request.path == carts_url %} active {% endif %}">
          <!-- session works in every page so -->
          <a class="nav-link" href="{% url 'carts:cart' %}"> <span class="cart-product-count"> {{ request.session.cart_items }} </span>Carts</a>
        </li>

      </ul>
      {% include 'search/snippets/search-form.html' %}
    </div>
  </div>
</nav>