carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('carts/',views.cart_home,name='cart'),
    path('cart_update/',views.cart_update,name='cart_update'),
    path('checkout/',views.checkout,name='checkout'),
    path('checkout/done',views.checkout_done_view,name='checkout_done'),
    path('api/cart/',views.api_cart_remove_view,name='api_cart_remove')

]

products/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'products'

urlpatterns = [
    path('products/',views.ProductListView.as_view(),name='product'),
    path('featured/',views.ProductFeaturedList.as_view(),name='featured'),

    #path('products/<str:pk>/',views.ProductDetailView.as_view()),
    path('featured/<str:pk>/',views.ProductFeaturedDetail.as_view(),name='singleFeatured'),
    path('products/<slug:slug>/',views.ProductDetailSlugView.as_view(),name='singleProduct')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#above code displays files uploaded

products/models.py
import random
import os

from django.urls import reverse
from django.db import models
from django.db.models.signals import pre_save, post_save

from django.db.models import Q

from ecommerce.utils import *

class ProductManager(models.Manager):

    def get_by_id(self,id):
        instance = self.get_queryset().filter(id=id)
        if instance.count() == 1:
            return instance.first()
        return None

    def featured(self):
        return self.get_queryset().filter(featured=True)

    def search(self,query):
        #using lookups and also using related field of many to many using tag and product
        lookups = Q(title__icontains=query)|Q(description__icontains=query)|Q(price__icontains=query)|Q(tag__title__icontains=query)
        return self.get_queryset().filter(lookups).distinct()

# Create your models here.
class Product(models.Model):
    title       = models.CharField(max_length=120)
    slug        = models.SlugField(blank=True,unique=True,allow_unicode=True)
    description = models.TextField()
    price       = models.DecimalField(decimal_places=2,max_digits=10,default=39.99)
    image       = models.FileField(upload_to='products', null=True,blank=True)
    featured    = models.BooleanField(default=False)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = ProductManager()
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('products:singleProduct', kwargs={'slug':self.slug})

#this is a signal method receiver
def product_pre_save_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

#connect this signal method with sender
pre_save.connect(product_pre_save_receiver,sender=Product)

products/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.shortcuts import render,get_object_or_404

from analytics.mixins import ObjectViewedMixin

from .models import *
from carts.models import Cart

# Create your views here.
class ProductDetailSlugView(ObjectViewedMixin,DetailView):
    queryset = Product.objects.all()
    template_name = 'products/detail.html'

    def get_context_data(self,*args,**kwargs):
        context = super(ProductDetailSlugView, self).get_context_data(*args,**kwargs)
        #this new_or_get returns two thing card_obj and new_obj
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

    def get_object(self,*args,**kwargs):
        request = self.request
        slug = self.kwargs.get('slug')

        instance = get_object_or_404(Product,slug=slug)
        return instance

class ProductFeaturedList(ListView):
    model = Product
    template_name = 'products/list.html'

    def get_queryset(self,*args,**kwargs):
        return Product.objects.featured()

class ProductFeaturedDetail(ObjectViewedMixin,DetailView):
    queryset = Product.objects.featured()
    template_name = 'products/detail.html'

class ProductListView(ListView):
    model = Product
    template_name = 'products/list.html'

class ProductDetailView(ObjectViewedMixin,DetailView):
    queryset = Product.objects.all()
    template_name = 'products/detail.html'

    def get_context_data(self,*args,**kwargs):
        context = super(ProductDetailView,self).get_context_data(*args,**kwargs)
        return context

products/templates/products/snippets/card.html
<div class="card" style="width: 18rem;">
  {% if product.image  %}
    <a href="{{ product.get_absolute_url }}">
    <img class="card-img-top" src="{{product.image.url}}" alt="Card image cap"></a>
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">{{product.title}}</h5>
    <p class="card-text">{{product.description|linebreaks|truncatewords:15}}</p>
    <!--<a href="{% url 'products:singleProduct' slug=product.slug %}" class="btn btn-primary">View</a>-->
    <a href="{{ product.get_absolute_url }}" class="btn btn-primary">View</a>
  </div>
</div>

products/templates/products/snippets/update_cart.html
<!-- This form can be used by any page and can be modified according to their use by passing the varibale and using include in their page -->

  <form method="POST" class="form-product-ajax" action="{% url 'carts:cart_update' %}" data-endpoint="{% url 'carts:cart_update' %}">
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{product.id}}">

  <!-- in cart is true, then this goes to cart home page -->
    {% if in_cart %}
      <button type="submit" class="btn btn-link btn-sm">Remove</button>
    <!-- if in cart is false, this goes to product detail -->
    {% else %}

    <span class="submit-span" >
      {% if product in cart.products.all %}
        In Cart<button type="submit" class="btn btn-link">Remove</button>
      {% else %}
        <button type="submit" class="btn btn-link">Add to cart</button>
      {% endif %}
    </span>

    {% endif %}

  </form>