carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('carts/',views.cart_home,name='cart'),
    path('cart_update/',views.cart_update,name='cart_update'),
    path('checkout/',views.checkout,name='checkout'),
    path('checkout/done',views.checkout_done_view,name='checkout_done'),
    path('api/cart/',views.api_cart_remove_view,name='api_cart_remove')

]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('search/',views.SearchProductView.as_view(),name='query')
]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render
from products.models import Product
from django.views.generic import ListView

# Create your views here.
class SearchProductView(ListView):
    template_name = 'search/view.html'

    def get_queryset(self,*args,**kwargs):
        request = self.request
        #use GET method from the submit value
        method_dict = request.GET
        #store the item from
        search_item = method_dict.get('q',None)

        if search_item is not None:
            return Product.objects.search(search_item)
        #displays if nothing is searched or matched
        return Product.objects.featured()

    def get_context_data(self,*args,**kwargs):
        #general inheritance
        context = super(SearchProductView,self).get_context_data(*args,**kwargs)
        #setting value to query with input searched item
        context['query'] = self.request.GET.get('q')

        return context

search/templates/search/snippets/search-form.html
<form method="GET" class="form my-2 my-lg-0 search-form" action="{% url 'search:query' %}">
  <div class="input-group">
    <input class="form-control" type="search" name='q' placeholder="Search" value='{{ request.GET.q }}'>
    <span class="input-group-btn">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </span>
  </div>
</form>